import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "견적 관리",
      items: [
        {
          type: "category",
          label: "포장보스 상품 요청",
          items: [
            {
              type: "doc",
              id: "req-boss-product/requested/index",
              label: "포장보스 상품 요청",
            },
            {
              type: "doc",
              id: "req-boss-product/estimate/index",
              label: "상품 견적 작성",
            },
            {
              type: "doc",
              id: "req-boss-product/confirmed/index",
              label: "최종 견적 확인",
            },
            {
              type: "doc",
              id: "req-boss-product/completed/index",
              label: "상품 등록 완료",
            },
            {
              type: "doc",
              id: "req-boss-product/all/index",
              label: "모든 단계 보기",
            },
          ],
        },
        {
          type: "doc",
          id: "req-fbv-product/index",
          label: "직거래 상품 요청",
        },
        {
          type: "doc",
          id: "pv-estimate/index",
          label: "견적 조회",
        },
      ],
    },
    {
      type: "category",
      label: "재고 발주 관리",
      items: [
        {
          type: "doc",
          id: "purchase-order/lines/track-inventory/draft/index",
          label: "재고 발주",
        },
        {
          type: "doc",
          id: "purchase-order/lines/track-inventory/pending-or-rejected/index",
          label: "접수대기 및 거부",
        },
        {
          type: "doc",
          id: "purchase-order/lines/track-inventory/receive/index",
          label: "대행 접수",
        },
        {
          type: "doc",
          id: "purchase-order/lines/track-inventory/in-production/index",
          label: "생산 중",
        },
        {
          type: "doc",
          id: "purchase-order/lines/track-inventory/dispatch-fulfillment/index",
          label: "대행 출고 지시",
        },
        {
          type: "doc",
          id: "purchase-order/lines/track-inventory/req-epd-update/index",
          label: "납품예정일 변경 요청",
        },
        {
          type: "doc",
          id: "purchase-order/lines/track-inventory/req-split-delivery/index",
          label: "분납 요청",
        },
        {
          type: "doc",
          id: "purchase-order/lines/track-inventory/confirm-delivery/index",
          label: "대행 배송 확정(택배)",
        },
        {
          type: "doc",
          id: "purchase-order/lines/track-inventory/print-invoice/index",
          label: "거래명세서 출력",
        },
        {
          type: "doc",
          id: "purchase-order/lines/track-inventory/inspect/index",
          label: "입고 검수",
        },
        {
          type: "doc",
          id: "purchase-order/lines/track-inventory/add-stock/index",
          label: "재고 입고",
        },
        {
          type: "doc",
          id: "purchase-order/lines/track-inventory/complete-delivery/index",
          label: "배송 완료 확인",
        },
        {
          type: "doc",
          id: "purchase-order/lines/track-inventory/all-status/index",
          label: "전체 발주 내역",
        },
      ],
    },
    {
      type: "category",
      label: "주문 관리",
      items: [
        {
          type: "doc",
          id: "orders/all/index",
          label: "전체 주문 리스트",
        },
        {
          type: "doc",
          id: "orders/order-detail-all/index",
          label: "전체 주문상세 리스트",
        },
        {
          type: "doc",
          id: "orders/type-a/index",
          label: "일반 주문 리스트",
        },
        {
          type: "doc",
          id: "orders/order-detail-a/index",
          label: "일반 주문상세 리스트",
        },
        {
          type: "doc",
          id: "orders/refunded-a/index",
          label: "일반 환불 리스트",
        },
        {
          type: "doc",
          id: "orders/type-b/index",
          label: "대행 주문 리스트",
        },
        {
          type: "doc",
          id: "orders/order-detail-b/index",
          label: "대행 주문상세 리스트",
        },
        {
          type: "doc",
          id: "orders/refunded-b/index",
          label: "대행 환불 리스트",
        },
        {
          type: "doc",
          id: "orders/type-c/index",
          label: "오픈몰 주문 리스트",
        },
        {
          type: "doc",
          id: "orders/order-detail-c/index",
          label: "오픈몰 주문상세 리스트",
        },
        {
          type: "doc",
          id: "orders/refunded-c/index",
          label: "오픈몰 환불 리스트",
        },
        {
          type: "doc",
          id: "orders/order-detail-d/index",
          label: "기타 배송 주문상세 리스트",
        },
      ],
    },
    {
      type: "category",
      label: "위탁 관리",
      items: [
        {
          type: "doc",
          id: "orders/lines-b/purchase/index",
          label: "발주서 작성",
        },
        {
          type: "doc",
          id: "purchase-order/lines/consignment/draft/index",
          label: "협력사 발주",
        },
        {
          type: "doc",
          id: "purchase-order/lines/consignment/pending-or-rejected/index",
          label: "접수대기 및 거부",
        },
        {
          type: "doc",
          id: "purchase-order/lines/consignment/receive/index",
          label: "대행 접수",
        },
        {
          type: "doc",
          id: "purchase-order/lines/consignment/in-production/index",
          label: "생산 중",
        },
        {
          type: "doc",
          id: "orders/lines-b/fulfill-by-courier/index",
          label: "대행 출고 지시(택배-일반)",
        },
        {
          type: "doc",
          id: "orders/lines-b/fulfill-by-courier-price-adjust/index",
          label: "대행 출고 지시(택배-납품 시 금액 확정)",
        },
        {
          type: "doc",
          id: "orders/lines-b/fulfill-by-non-courier/index",
          label: "대행 출고 지시(화물차)",
        },
        {
          type: "doc",
          id: "purchase-order/lines/consignment/req-epd-update/index",
          label: "납품예정일 변경 요청",
        },
        {
          type: "doc",
          id: "orders/delivery-b-by-courier/index",
          label: "대행 배송 확정(택배)",
        },
        {
          type: "doc",
          id: "orders/delivery-b-by-non-courier/index",
          label: "대행 배송 확정(화물차)",
        },
        {
          type: "doc",
          id: "purchase-order/lines/consignment/print-invoice/index",
          label: "거래명세서 출력",
        },
        {
          type: "doc",
          id: "purchase-order/lines/consignment/complete-delivery/index",
          label: "배송 완료 확인",
        },
        {
          type: "doc",
          id: "purchase-order/lines/consignment/all-status/index",
          label: "전체 발주 내역",
        },
      ],
    },
    {
      type: "category",
      label: "B2B",
      items: [
        {
          type: "category",
          label: "주문",
          items: [
            {
              type: "doc",
              id: "b2b/order/accept/index",
              label: "주문 접수",
            },
            {
              type: "doc",
              id: "b2b/order/all/index",
              label: "전체 주문 내역",
            },
          ],
        },
        {
          type: "doc",
          id: "b2b/purchase-write/index",
          label: "발주서 작성",
        },
        {
          type: "category",
          label: "발주",
          items: [
            {
              type: "doc",
              id: "b2b/purchase-order/lines/consignment/draft/index",
              label: "협력사 발주",
            },
            {
              type: "doc",
              id: "b2b/purchase-order/lines/consignment/pending-or-rejected/index",
              label: "접수대기 및 거부",
            },
            {
              type: "doc",
              id: "b2b/purchase-order/lines/consignment/receive/index",
              label: "대행 접수",
            },
            {
              type: "doc",
              id: "b2b/purchase-order/lines/consignment/in-production/index",
              label: "생산 중",
            },
            {
              type: "doc",
              id: "b2b/orders/lines-b/fulfill-by-non-courier/index",
              label: "대행 출고 지시",
            },
            {
              type: "doc",
              id: "b2b/purchase-order/lines/consignment/req-epd-update/index",
              label: "납품예정일 변경 요청",
            },
            {
              type: "doc",
              id: "b2b/purchase-order/lines/consignment/req-split-delivery/index",
              label: "분납 요청",
            },
            {
              type: "doc",
              id: "b2b/orders/delivery-b/index",
              label: "대행 배송 확정",
            },
            {
              type: "doc",
              id: "b2b/purchase-order/lines/consignment/print-invoice/index",
              label: "거래명세서 출력",
            },
            {
              type: "doc",
              id: "b2b/purchase-order/lines/consignment/complete-delivery/index",
              label: "배송 완료 확인",
            },
            {
              type: "doc",
              id: "b2b/purchase-order/lines/consignment/all-status/index",
              label: "전체 발주 내역",
            },
          ],
        },
        {
          type: "category",
          label: "매출 정산",
          items: [
            {
              type: "doc",
              id: "b2b/settlement/all/index",
              label: "전체 매출 내역",
            },
            {
              type: "doc",
              id: "b2b/settlement/in-progress/index",
              label: "매출 정산",
            },
            {
              type: "doc",
              id: "b2b/settlement/edit-request/index",
              label: "수정 요청",
            },
            {
              type: "doc",
              id: "b2b/settlement/closing-statement/index",
              label: "마감명세서 발송",
            },
            {
              type: "doc",
              id: "b2b/settlement/pending/index",
              label: "대행 매출 확정",
            },
            {
              type: "doc",
              id: "b2b/settlement/closed/index",
              label: "매출 마감",
            },
            {
              type: "doc",
              id: "b2b/settlement/taxinvoice/index",
              label: "매출 세금계산서",
            },
          ],
        },
        {
          type: "doc",
          id: "b2b/sales-stats/brand/index",
          label: "월별 매출 내역",
        },
        {
          type: "category",
          label: "매입 정산",
          items: [
            {
              type: "doc",
              id: "b2b/purchases/boss/standby-or-pending/index",
              label: "매입 정산",
            },
            {
              type: "doc",
              id: "b2b/purchases/boss/revision/index",
              label: "매입 수정 요청",
            },
            {
              type: "doc",
              id: "b2b/purchases/boss/pending/index",
              label: "대행 매입 확정",
            },
            {
              type: "doc",
              id: "b2b/purchases/boss/closed/index",
              label: "매입 마감",
            },
            {
              type: "doc",
              id: "b2b/purchases/boss/all-status/index",
              label: "전체 매입 내역",
            },
          ],
        },
        {
          type: "doc",
          id: "b2b/stats/purchases/vendor/index",
          label: "월별 매입 내역",
        },
      ],
    },
  ],
};

export default sidebars;
